#!/usr/bin/env bash

_pr_completions() {
    local cur prev alias
    COMPREPLY=()
    cur="${COMP_WORDS[COMP_CWORD]}"
    prev="${COMP_WORDS[COMP_CWORD-1]}"

    COMPREPLY=($(compgen -W "-h --help -c --count -s --size --csv abandoned active all completed" -- ${cur}))
}

complete -F _pr_completions pr


